# Site settings
title: SDN Application Development With Brocade SDN Controller
email: jeb@elbrys.com
description: > # this means to ignore newlines until "baseurl:"
  Tutorials and ideas for application developers, network administrators and 
  DevOps to program their network.
baseurl: "/BVC" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jebpublic
github_username:  jebpublic

# Build settings
markdown: kramdown
